<?php
return [
	/*
    |--------------------------------------------------------------------------
    | User Defined Variables
    |--------------------------------------------------------------------------
    |
    | This is a set of variables that are made specific to this application
    | that are better placed here rather than in .env file.
    | Use config('your_key') to get the values.
    |
	*/
	'admin' => env('ADMIN', false) === true,
	'timezone' => env('APP_TIMEZONE', 'UTC'),
	'clientTimeMaxHoursOld' => 24 * 30, // One month so people can be offline and sync later.
	'clientTimeMaxHoursAhead' => 14,
	'throttleLimit' => env('THROTTLE_LIMIT', 60),
	'throttleInterval' => intval(env('THROTTLE_INTERVAL_IN_MINS', 1)),
	'identity' => [
		'refLength' => 6,
		'refMaxLength' => 16,
		'emailMaxLength' => 255,
		'resetTokenMaxLength' => 20,
	],
	'impression' => ['refLength' => 9],
	'ruleMessages' => [
		// Laravel Rules
		'required' => 'The :attribute field is required.',
		'required_with' => 'The :attribute field is required.',
		'min' => 'The :attribute field exceeded the min limit of :min.',
		'max' => 'The :attribute field exceeded the max limit of :max.',
		'numeric' => 'The :attribute field must have numeric value.',
		'boolean' => 'The :attribute field must have boolean value.',
		'exists' => 'This :attribute [:input] does not exist.',
		'unique' => 'This :attribute already exists.',
		'email' => 'This :attribute field is not a valid email.',
		'date' => 'This :attribute field is not a valid date.',
		'url' => 'This :attribute field is not a valid url.',
		'before' => 'This :attribute field is not a valid date.',
		'after' => 'This :attribute field is not a valid date.',
		'file' => ':attribute field is not a valid file.',
		'array' => ':attribute field is not a valid array.',
		'between' => ':attribute field is not between the allowed values.',
		'filled' => ':attribute field is null or empty.',
		'string' => 'The :attribute field is not a valid string.',
		'json' => 'The :attribute field is not a valid json.',
		'in' => 'This :attribute [:input] is not valid.',
		'required_with' => 'The :attribute field is required.',
		// Custom Rules
		'valid_text' => 'This :attribute field is not a valid text.',
		'valid_name' => 'This :attribute field is not a valid name.',
		'valid_user_name' => 'This :attribute field is not a valid username.',
		'valid_email' => 'This :attribute field is not a valid email.',
		'valid_ref' => 'This :attribute field is not a valid ref or key.',
		'valid_handle' => 'This :attribute field is not a valid handle.',
		'valid_source' => 'This :attribute field is not a valid source.',
		'valid_flow' => 'This :attribute field is not a valid flow.',
		'valid_client' => 'This :attribute field is not a valid client.',
		'valid_version' => 'This :attribute field is not a valid version.',
		'valid_rating' => 'This :attribute field is not a valid rating.',
		'valid_price' => 'This :attribute field is not a valid price.',
		'valid_long_text' => 'This :attribute field is not a valid long text.',
		'valid_subject_name' => 'This :attribute field is not a valid subject name.',
		'non_print' => 'This :attribute field contains non-printable chars.',
		'non_print_or_tags' => 'This :attribute field contains non-printable or html chars.',
		'sha256' => 'This :attribute field is not a valid sha256.',
		'base64' => 'The :attribute field is not a valid base64 string.',
		'not_string' => ':attribute field should not be a string.',
		'valid_latitude' => 'The :attribute field is not a valid latitude.',
		'valid_longitude' => 'The :attribute field is not a valid longitude.',
		'valid_region' => 'The :attribute field is not a valid region.',
		'valid_phone_prefix' => 'The :attribute field is not a valid phone prefix.',
		'valid_phone' => 'The :attribute field is not a valid phone.',
		'valid_client_host' => '[:input] is not a valid client host.',
		'valid_voucher_code' => '[:input] is not a valid voucher code.',
		'valid_hjson' => 'The :attribute field is not a valid json.',
		'valid_fkey' => 'The :attribute field is not a valid fkey value.',
		// Message Only
		'valid_voucher' => 'The :attribute field is not a valid voucher code.',
		'voucher_limit' => 'Voucher has reached its usage limit and is no longer valid.',
		'mailchimp_error' => 'Mailchimp error detected.',
	],
	'errorCodes' => [
		// Laravel Rules
		'required' => 'field_is_required',
		'requiredwith' => 'field_is_required_with',
		'max' => 'field_exceeded_max',
		'numeric' => 'field_not_numeric',
		'boolean' => 'field_not_boolean',
		'exists' => 'field_does_not_exists',
		'unique' => 'field_is_not_unique',
		'email' => 'invalid_email',
		'date' => 'invalid_date',
		'url' => 'invalid_url',
		'before' => 'invalid_before_date',
		'after' => 'invalid_after_date',
		'file' => 'invalid_file',
		'array' => 'invalid_array',
		'filled' => 'field_not_filled',
		'between' => 'field_not_between',
		'string' => 'invalid_string',
		'json' => 'invalid_json',
		'requiredwith' => 'field_is_required_with',
		// Custom Rules
		'invalid_text' => 'invalid_text',
		'invalid_name' => 'invalid_name',
		'invalid_user_name' => 'invalid_user_name',
		'invalid_email' => 'invalid_email',
		'invalid_ref' => 'invalid_ref',
		'invalid_handle' => 'invalid_handle',
		'invalid_client' => 'invalid_client',
		'invalid_version' => 'invalid_version',
		'invalid_rating' => 'invalid_rating',
		'invalid_price' => 'invalid_price',
		'invalid_source' => 'invalid_source',
		'invalid_stats' => 'invalid_stats',
		'invalid_note' => 'invalid_note',
		'invalid_lang' => 'invalid_lang',
		'invalid_long_text' => 'invalid_long_text',
		'invalid_subject_name' => 'invalid_subject_name',
		'non_print' => 'non_printable_chars_found',
		'non_print_or_tags' => 'non_printable_chars_or_tags_found',
		'sha256' => 'invalid_sha256',
		'not_string' => 'field_must_not_be_a_string',
		'invalid_latitude' => 'invalid_latitude',
		'invalid_longitude' => 'invalid_longitude',
		'invalid_phone_prefix' => 'invalid_phone_prefix',
		'invalid_phone' => 'invalid_phone',
		'invalid_region' => 'invalid_region',
		'invalid_hjson' => 'invalid_hjson',
		// Error Code Only
		'invalid_payload' => 'invalid_payload',
		'invalid_access' => 'invalid_access',
		'invalid_team_access' => 'invalid_team_access',
		'invalid_entity_access' => 'invalid_entity_access',
		'invalid_note_type' => 'invalid_note_type',
		'invalid_object' => 'invalid_object',
		'invalid_file' => 'invalid_file',
		'invalid_file_mime_type' => 'invalid_file_mime_type',
		'invalid_file_ext_type' => 'invalid_file_ext_type',
		'invalid_file_size' => 'invalid_file_size',
		'invalid_identity' => 'invalid_identity',
		'invalid_username_or_password' => 'invalid_username_or_password',
		'invalid_token' => 'invalid_token',
		'invalid_email' => 'invalid_email',
		'invalid_search_key' => 'invalid_search_key',
		'invalid_template' => 'invalid_template',
		'user_does_not_exist' => 'user_does_not_exist',
		'user_credentials' => 'invalid_credentials',
		'subscription_error_local' => 'subscription_error_local',
		'subscription_error_remote' => 'subscription_error_remote',
		'already_subscribed_local' => 'already_subscribed_local',
		'already_subscribed_remote' => 'already_subscribed_remote',
		'trial_used_local' => 'trial_used_local',
		'trial_used_remote' => 'trial_used_remote',
		'voucher_limit' => 'voucher_limit',
		'invalid_voucher' => 'invalid_voucher',
		'team_already_member' => 'team_already_member',
		'team_already_join' => 'team_already_join',
		'team_no_pending_join_request' => 'team_no_pending_join_request',
		'team_invalid_action' => 'team_invalid_action',
		'team_invalid_role' => 'team_invalid_role',
		'invalid_property' => 'invalid_property',
		'invalid_impression_info' => 'valid_impression_info',
		'team_invalid_copy' => 'team_invalid_copy',
		'valid_voucher' => 'invalid_voucher',
		'voucher_limit' => 'already_reached_voucher_usage_limit',
		'impression_on_collection' => 'impression_on_collection',
		'mail_error' => 'mail_error',
		'contest_not_participant' => 'contest_not_participant',
		'contest_not_assigned' => 'contest_not_assigned',
		'relation_exists' => 'relation_exists',
		'unexpected' => 'unexpected',
		'mailchimp' => 'mailchimp_error',
		'invalid_invite_ref' => 'invalid_invite_ref',
		'fkey_updating_not_allowed' => 'fkey_updating_not_allowed',
		'fkey_field_not_allowed' => 'fkey_field_not_allowed',
		'fkey_origin_invalid' => 'fkey_origin_invalid',
	],
	'fileErrorMessages' => [
		// Note: file error messages were based on official PHP definitions - http://php.net/manual/en/features.file-upload.errors.php
		0 => 'There is no error, the file uploaded with success',
		1 => 'The uploaded file exceeds the upload_max_filesize directive in php.ini',
		2 => 'The uploaded file exceeds the MAX_FILE_SIZE directive that was specified in the HTML form',
		3 => 'The uploaded file was only partially uploaded',
		4 => 'No file was uploaded',
		6 => 'Missing a temporary folder',
		7 => 'Failed to write file to disk.',
		8 => 'A PHP extension stopped the file upload.',
	],
	'file' => [
		'refLength' => 6,
	],
	'fileUpload' => [
		'allowedFiles' => [
			'images' => [
				'ext' => ['png', 'jpg', 'jpeg'],
				'mime' => ['image/png', 'image/jpg', 'image/jpeg'],
				'maxBytes' => 10485760,
			],
			'documents' => [
				'ext' => ['txt', 'pdf', 'docx', 'xlsx', 'pptx'],
				'mime' => [
					'text/plain',
					'application/pdf',
					'application/msword',
					'application/vnd.ms-excel',
					'application/vnd.ms-powerpoint',
				],
				'maxBytes' => 10485760,
			],
			'json' => [
				'ext' => ['json'],
				'mime' => ['text/plain', 'application/json'],
				'maxBytes' => 10485760,
			],
		],
	],
	'event' => [
		'validVisibility' => ['open', 'hidden', 'private'],
	],
	'team' => [
		'roles' => [
			'traditional' => ['owner', 'admin', 'editor', 'member'],
			'contest' => ['owner', 'admin', 'participant'],
			'division' => ['leader', 'guide', 'member'],
		],
	],
	'notes' => [
		'validType' => ['@', 'nose', 'palate'],
	],
	'devRefs' => ['TEX', 'TEY', 'TEZ'],
	'log' => [
		'400' => env('LOG_400'),
		'500' => env('LOG_500'),
		'sqlLogsDir' => env('LOG_SQL'),
		'sqlExecution' => env('LOG_SQL_LONGER_THAN_MS', 500),
	],
	'mail' => [
		'host' => env('MAIL_HOST'),
		'mailWhenDev' => env('MAIL_WHEN_DEV', false),
		'mailWhenDevForce' => env('MAIL_WHEN_DEV_FORCE', false),
		'mailOnSignup' => env('MAIL_ON_SIGNUP', false),
	],
	'ownTerms' => [
		'coupon' => 'voucher',
	],
	'search' => [
		'max_return_size' => 10,
	],
	'mailChimp' => [
		'autoSubscribe' => env('MAILCHIMP_ON_SIGNUP', false),
		'apiKey' => env('MAILCHIMP_API_KEY', 'b897486dbeff808302ad9cec19673af0-us3'),
		'listId' => env('MAILCHIMP_LIST_ID', '3138db585e'),
	],
	'fkey_allowed_properties' => [
		'origin',
		'subject_key',
		'event_key',
		'client_key',
		'producer_key',
	],
	'fkey_allowed_origin_values' => ['BB', 'TST'],
];
